[movieflix]
# Example target host. Replace 'app.example.com' by your VM/server IP or hostname.
# For a local test, use: localhost ansible_connection=local
app.example.com ansible_user=ubuntu

[movieflix:vars]
project_root=/opt/movieflix
